twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']


    globals:
        anterior-4: 2020
        anterior-3: 2021
        anterior-2: 2022
        anterior-1: 2023
        anterior: 2024
        actual: 2025
        siguiente: 2026
        abierto: 2025-01-01
        cerrado: 2026-02-20