<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventosRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('fechaActividad' => 'ASC'));
    }

    public function findEventos($informe_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM App:Eventos s
                    JOIN s.informe f
                    WHERE f.id = :informe
                    AND s.tipo <> :tipo
                    ORDER BY s.fechaInicio ASC"
            )
            ->setParameter('informe', $informe_id)
            ->setParameter('tipo', 'Visitante')
            ->getResult();
    }

    public function findByVisitantes($informe_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM App:Eventos s
                    JOIN s.informe f
                    WHERE f.id = :informe
                    AND s.tipo = :tipo
                    ORDER BY s.fechaInicio ASC"
            )
            ->setParameter('informe', $informe_id)
            ->setParameter('tipo', 'Visitante')
            ->getResult();
    }
}