<?php


namespace App\Repository;

use App\Entity\Academico;
use App\Entity\Informe;

use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;

/**
 * InformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Informe[]    findAll()
 */
class InformeRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Informe::class);
    }

    public function findOneByAnio($anio, $academico)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT i FROM App:Informe i
                    JOIN i.academico a
                    WHERE a.id = :academico
                    AND i.anio = :anio"
            )
            ->setParameter('academico', $academico)
            ->setParameter('anio', $anio)
            ->getSingleResult();
    }

    public function findByActivo($anio)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT i FROM App:Informe i
                    JOIN i.academico a
                    WHERE a.activo = :activo
                    AND i.anio = :anio
                    ORDER BY a.apellido ASC"
            )
            ->setParameter('activo', true)
            ->setParameter('anio', $anio)
            ->getResult();
    }
}