<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PosdocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosdocRepository extends EntityRepository
{
}