<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectosRepository extends EntityRepository
{
}