#index:
#    path: /
#    controller: App\Controller\DashController::indexAction

# redirecting the homepage
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: dashboard
    permanent: true
    keepQueryParams: true

fos_user_profile_show:
  path: /dash/
